import { readJsonFileSync } from "./json.js";

/**
 * The committed allowlist of public exports for the pinned
 * Fluent UI React v9 release.
 *
 * Rules and patterns may only name an export that appears here. The file is
 * generated by `scripts/extract-facts.ts` from the sibling API-fact source and
 * is committed so the validation gates never need the sibling repository or the
 * network at check time.
 */
export interface VerifiedExportsFact {
  /** The package whose runtime exports were recorded. */
  package: string;
  /** The exact installed version the exports were read from. */
  version: string;
  /** The sibling API-fact commit the allowlist is pinned to. */
  sourceCommit: string;
  /** The schema document version the cross-check used. */
  schemaVersion: string;
  /** A human-readable description of the generating input. */
  generatedFrom: string;
  /** Every public export name, sorted alphabetically. */
  exports: string[];
}

/** Repository-relative path of the committed allowlist. */
export const FACTS_JSON_PATH = "facts/verified-exports.json";

/**
 * Validate the shape of a parsed allowlist document.
 *
 * The allowlist is small and internal, so a lightweight structural check is
 * enough; the important guarantee is that the `exports` list contains only
 * non-empty strings, because every entry is treated as a trusted name.
 *
 * @param data - Parsed JSON read from {@link FACTS_JSON_PATH}.
 * @returns The typed allowlist document.
 * @throws Error when a required field is missing or mistyped.
 */
export function parseVerifiedExports(data: unknown): VerifiedExportsFact {
  if (typeof data !== "object" || data === null || Array.isArray(data)) {
    throw new Error(`${FACTS_JSON_PATH} must contain a JSON object`);
  }
  const record = data as Record<string, unknown>;
  const stringField = (name: keyof VerifiedExportsFact): string => {
    const value = record[name];
    if (typeof value !== "string" || value.length === 0) {
      throw new Error(`${FACTS_JSON_PATH} field "${String(name)}" must be a non-empty string`);
    }
    return value;
  };
  const rawExports = record["exports"];
  if (!Array.isArray(rawExports) || rawExports.length === 0) {
    throw new Error(`${FACTS_JSON_PATH} field "exports" must be a non-empty array`);
  }
  const exports = rawExports.map((value) => {
    if (typeof value !== "string" || value.length === 0) {
      throw new Error(`${FACTS_JSON_PATH} "exports" entries must be non-empty strings`);
    }
    return value;
  });

  return {
    package: stringField("package"),
    version: stringField("version"),
    sourceCommit: stringField("sourceCommit"),
    schemaVersion: stringField("schemaVersion"),
    generatedFrom: stringField("generatedFrom"),
    exports,
  };
}

/**
 * Read and type the committed allowlist from disk.
 *
 * @returns The typed allowlist document.
 * @throws Error when the file is missing or malformed.
 */
export function loadVerifiedExportsSync(): VerifiedExportsFact {
  return parseVerifiedExports(readJsonFileSync(FACTS_JSON_PATH));
}

/**
 * Build a fast membership set of allowed export names.
 *
 * @param fact - A typed allowlist document.
 * @returns A set containing every allowed export name.
 */
export function allowedExportNames(fact: VerifiedExportsFact): Set<string> {
  return new Set(fact.exports);
}
